- type: job
  id: Mercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 108000
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess

- type: startingGear
  id: MercenaryGear
  equipment:
    ears: ClothingHeadsetAltMercenary
