- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 43200
  startingGear: PilotGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  accessGroups: # Frontier
  - GeneralAccess

- type: startingGear
  id: PilotGear
  equipment:
    ears: ClothingHeadsetAltPilot
