- type: job
  id: FreeholderDSM
  name: job-name-freeholder
  description: job-description-freeholder
  playTimeTracker: JobFreeholderDSM
  weight: 73
  startingGear: FreeholderGear
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:FactionRequirement
        factionID: "DSM"
  special:
  - !type:AddComponentSpecial
    components:
      - type: LanguageKnowledge
        speaks:
          - SolCommon
        understands:
          - Tradeband
          - SolCommon
  alwaysUseSpawner: true
  icon: "JobIconImperialFreeholder"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Empire
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: FreeholderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialFreeholder
    id: FreeholderPDA
    ears: ClothingHeadsetEmpireCiv
    shoes: ClothingShoesBootsImperialLongboots
